---
docker_jenkins_image: docker-jenkins
docker_jenkins_container: docker-jenkins
docker_jenkins_home: "{{ docker_home }}/docker-jenkins"

jenkins_server_url: http://localhost
jenkins_port: 8080
jenkins_url: "{{ jenkins_server_url }}:{{ jenkins_port }}"

apt_packages:
  - python-pip

pip_packages:
  - ansible-lint
  
plugins:
  - ant
  - antisamy-markup-formatter
  - bouncycastle-api
  - build-timeout
  - email-ext
  - external-monitor-job
  - git-server
  - github-branch-source
  - gradle
  - icon-shim
  - ldap
  - matrix-auth
  - pam-auth
  - pipeline-github-lib
  - slack
  - ssh-slaves
  - subversion
  - timestamper
  - windows-slaves
  - workflow-aggregator
  - ws-cleanup